In [0]:
import pandas as pd
data={'Company':['NIKE','PUMA','MAC','MAC','BARMIN','NIKE'],
      'Product':['Shoe','socks','lipstick','foundation','eyeliner','shoe'],'Sale':[200,120,340,124,243,350]}

In [0]:
df = pd.DataFrame(data)

In [0]:
display(df)

Company,Product,Sale
NIKE,Shoe,200
PUMA,socks,120
MAC,lipstick,340
MAC,foundation,124
BARMIN,eyeliner,243
NIKE,shoe,350

In [0]:
bycomp=df.groupby('Company')

In [0]:
bycomp.describe()

In [0]:
byprod=df.groupby('Product')

In [0]:
byprod.describe()

In [0]:
bycomp.std()

,Sale
Company,
BARMIN,NaN
MAC,152.735065
NIKE,106.066017
PUMA,NaN

In [0]:
byprod.mean()

,Sale
Product,
Shoe,200
eyeliner,243
foundation,124
lipstick,340
shoe,350
socks,120

In [0]:
bycomp.describe().transpose()['MAC']

Out[17]: Sale  count      2.000000
      mean     232.000000
      std      152.735065
      min      124.000000
      25%      178.000000
      50%      232.000000
      75%      286.000000
      max      340.000000
Name: MAC, dtype: float64

In [0]:
byprod.describe().transpose()['shoe']

Out[19]: Sale  count      1.0
      mean     350.0
      std        NaN
      min      350.0
      25%      350.0
      50%      350.0
      75%      350.0
      max      350.0
Name: shoe, dtype: float64

In [0]:
byprod.std()

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<command-171234738438783> in <module>
----> 1 byprod.std()

NameError: name 'byprod' is not defined